### ISSUE TITLE
Unable to download a file to a CPE

### ISSUE THREAD

**Issue by margui1** [zaidka/genieacs#162]

**Comment by marcosleon22496** [comment]
I'm having the same problem, apparently the file is downloaded because in CWMP's terminal is reflected but the CPE is not updating its software version. Maybe the problem remains in the TR-069 client impementation on CPE.

![captura1](https://cloud.githubusercontent.com/assets/17618722/16681215/9a2bd058-44f3-11e6-8347-16d0bf7f5817.PNG)

**Comment by margui1** [comment]
Yes, I have the same info printed in the terminal from ACS side but it seems that the client doesn't even succeed to get the file. It received the download rpc method from the ACS and responded with the download response ( status:1). However, i can get directly on my own the file from the ACS server by calling wget http://ACSurl:7567/file_to_download.
