### ISSUE TITLE
Get ALL parameters from CPE Huawei EA360

### ISSUE THREAD

**Issue by Josevalcarcel21** [zaidka/genieacs#202]
Hello, I have mounted Genieacs on a server and I have connected a CPE Huawei ES360. I want the CPE to send me information of all the data (Id, signals, etc), but it only returns me some, from the CPE I see that if it has RSSI information etc, but the ACS server does not get that data.

Does anyone know why it can be and how to fix it?

**Comment by DrumSergio** [comment]
Hi @Josevalcarcel21 !

Please use the mailing list if you have this type of issues: http://lists.genieacs.com/
Anyway, it seems you are using v1.1 GenieACS (you have to put all the data you can in order to help you out). Assuming that, then you need to perform a refresh over InternetGatewayDevice. (Or the root parameter). GenieACS v1.1 works this way.
If you're using v1.0, then, it may exist a problem in the CPE implementation of CWMP protocol
