### ISSUE TITLE
Parameter Aliasing - do not pull from value of 0

### ISSUE THREAD

**Issue by agriff** [zaidka/genieacs#27]
Hello all,

I am testing some CPEs that will have downstream/upstream stats that can be read from multiple interfaces depending on which path they are going out on, for instance 
InternetGatewayDevice.WANDevice.1.WANDSLInterfaceConfig.DownstreamCurrRate
InternetGatewayDevice.WANDevice.2.WANDSLInterfaceConfig.DownstreamCurrRate
InternetGatewayDevice.WANDevice.3.WANDSLInterfaceConfig.DownstreamCurrRate
and so on. Only one of these will actually have a full value assigned to it at any given time, such as 51200, the others will all read as 0. 

What I am trying to do is have the device listing show the current downstream stats under a unified listing for the connected CPEs no matter which path they are going out. 

I have set up an alias in parameters.json 

"InternetGatewayDevice.WANDevice./^\d+$/.WANDSLInterfaceConfig.DownstreamCurrRate" : {"alias" : "summary.DownstreamCurrRate"},

and have this linked to index_parameters.yml

Current Downstream: summary.DownstreamCurrRate

but the gui shows the value as 0. I assume this is because it is reading both the value 51200 from the working interface and the value 0 from the nonworking interfaces. Is there a way to set up some sort of if then statement to have it pull only from an interface that is populated with a value other than 0? Or is there a better way to set this up? 

Thanks in advance.

**Comment by 5700** [comment]
Hi @ericl85, can you send me the patch you made for this.  

When using a single device in the ACS, the parameters.json file can be modified to select the correct parameter index that are not blank.  Now I am starting to use multiple devices in an ACS where the index number is changed.  More specifically, I have the same device with two different personalities on the network and using different firmware.  As a result the IP address of the device as known to the ACS is either from a WAN interface or a PPP connection.

It might be useful to have multiple parameters.json files that can be assigned to a particular device hardware and/or software, as well as the generic parameters.json file.

**Comment by 5700** [comment]
In regards to what @ericl85 wrote:
"I had a similar issue where I had two PPP WAN interfaces defined (in a DSL modem) and the inactive one had a blank IP Address, which kept overwriting the summary.ip alias.

I just changed it so it would only update an alias if the updated value is not 0 or blank."


Can someone point me to where I can implement this myself, or provide a patch.

I have similar devices that use different interfaces (WAN or PPP) when talking to ACS.  It would be good if the IP could be picked up instead of matching on 'blank'.

**Comment by zaidka** [comment]
I originally thought I'd implement that kind of enhancement to aliases, but the plan was scrapped because it wouldn't be flexible and certainly not scalable. A better solution is coming in the next release where you can create custom virtual parameters with a script. I know the next release is long over due, very sorry about that. Doing my best to release it soon.

**Comment by akcoder** [comment]
Thank you for all your hard work Zaid!
