### ISSUE TITLE
Download vendor configuration to multiple CPE

### ISSUE THREAD

**Issue by kroshell** [zaidka/genieacs#42]
Hello Zaidka,

Would appreciate you assistance on this issue. I'm using the API to create vendor configuration files to be automatically downloaded to a range of CPE defined by the fields: OUI, Product Class and Version (assuming this is hardware version).

I created the files successfully, but the ACS never sends to the CPEs. I would have to manually "Push File" from the device screen.

Thank you,
David

**Comment by LuCe86** [comment]
Hi everyone
I have a similar problem to slyruss, in fact I want to add a factory reset as task to my cpe after the download (and subsequent reboot) of a new firmware.
When I try, I can’t do this because the cpe doesn’t complete the transfer.
I have a similar problem to slyruss, in fact I want to add a factory reset as task to my cpe after the download (and subsequent reboot) of a new firmware.
When I try, I can’t do this because the cpe doesn’t complete the transfer.
thank you
