### ISSUE TITLE
Download configuration and firmware automatically

### ISSUE THREAD

**Issue by lorenzo8769** [zaidka/genieacs#77]
Hi all,

What is the correct configuration for CPE automatically download a configuration file and firmware.

Thank you in advance.

Best Regards,
Laurent

**Comment by lorenzo8769** [comment]
I want to have a really full documentation to set genieACS . Today I can not automate the download of a configuration file , update the router or router to have all the technical information.  

Best Regards,
Laurent

**Comment by zaidka** [comment]
You need to define a preset with a "software" version configuration and have the corresponding firmware image uploaded. Note though that since the firmware upgrade is usually a service disrupting process, the ACS will only push the file when the CPE checks for firmware update (not all devices support that). To actively push firmware updates without waiting for the device to check, you'll need to use the API to queue upgrade tasks.

**Comment by lorenzo8769** [comment]
Thanks you very much for your reply. We can do the same for configuration files? We can define a directory with all the files of configuration (example: serial_number.ini) so the router can pick the configuration that is located in this directory automatically ? Excuse me for my english...

**Comment by zaidka** [comment]
No, you need to set your configuration in presets tab. Please experiment with that to try to understand how it works. Also, it would be best to use the mailing list for this kind of questions. This issue tracker is for reporting software issues; you'll get more responses from the community using the mailing list.
