### ISSUE TITLE
First device registration

### ISSUE THREAD

**Issue by eckertfo** [zaidka/genieacs#80]
Hi 

My setup is:
- easycwmp on the cpe
- geniacs on the ace
Everything works fine till i delete the genieacs monogdb database on the server and restart the genieacs programms. CPE Device will not registrat any more on the ace and no database entry will be created.

Everythings works fine and normal when i changed the url on the cpe of my easycwmp to a diffrent URL url 'http://10.1.3.41:7547' to  url 'http://10.1.3.41:7547/genieacs' and restart this

If I do this again deleting now this database and restart the genieacs programms i have to switch back the URL from 
url 'http://10.1.3.41:7547/genieacs' to  url 'http://10.1.3.41:7547'

My be have something miss understund? Or is this a normal behavier?

Kind regards

Flo

**Comment by zaidka** [comment]
Genie makes heavy use of caching so manipulating the database directly can have unpredictable results. Try clearing redis database too. Look at source of delete device API to see what cache keys get deleted when you delete a device.

As to why changing the ACS URL causes the ACS to register the device, it's because when the ACS URL changes the device sends a bootstrap event causing Genie to ignore cache and refresh the device.

**Comment by eckertfo** [comment]
Thank you very much for your fast response :-)
